### PR TITLE
Changes to allow multilingual. FR structure added.

### PR DESCRIPTION
**Pull request by lin-d-hop**
In this PR I've changed the structure of the User Guide repo to fit with the structure required for multilingual.

I tested this in a fresh Gitbook which you can take a look at here:
https://lin-d-hop.gitbooks.io/ofn-testing-changes/

There may well be a few things that are not right. I'm happy to look into this further and help out when you get stuck. This should be enough to allow the different language groups to begin translating.

Note that the FR folder is just a copy of the EN folder. Gitbook does not really support multilingual. You basically create a FULL copy of the original book and the translated version can diverge 100% from the original. There is no requirement for consistency to the original.

Thus it might actually be a better idea to create an entirely NEW gitbook for the different language groups. This was we could potentially have many more users able to directly access the gitbook source. Something to consider :-)

### CODE REVIEW

**Comment by RachL** [comment]
Hi @lin-d-hop We've had a look yesterday with @myriamboure and we've made a small study of the options we have here. It seems at first side that Gitbook is more user-friendly, but requires a wider set up process than using Github directly. A quick hangout on the subject in order to better understand the workflow when we want to update a guide in both cases would be great (if you are ok of course). I will try to set up a date.
The goal being afterwards to launch to french version quite quickly :)

image

**Comment by kirstenalarsen** [comment]
it took a bit of messing around but I suspect it will be worth it in set-up to get them syncing so that you can easily edit via either gitbook or github - like the master one is. I am unlikely to make the hangout (and will probably stuff up your time windows if I try) but happy to add notes / comments somewhere if that’s useful

**Comment by sstead** [comment]
Hey @lin-d-hop, can you help me? I used to edit the user guide here - https://www.gitbook.com/book/ofn-user-guide/ofn-user-guide-master/details but there's still an error there that means I can't save any changes. I understand you've been playing with the different language versions (which is great, thanks), but I don't understand how that relates to where I need to go to maintain the master english Gitbooks guide? Thanks!

**Comment by myriamboure** [comment]
One of the main issue we identified with Rachel was that in GitHub, it's really not user friendly to see the menu organization, if you want to create a new page you don't know wich nomenclature to use to make sure it will be synchronized with Gitbook. Like the files are in some kind of random order in the GH repo... maybe we can reorganize the repos in GH and maintaint the sync with Gitbook, so that way we could make it more user friendly in GH as well? Anyway, let's discuss in a call, probably Europe + Sally to start with to make it easier with time differences.

**Comment by lin-d-hop** [comment]
Hi @sstead 
The recent changes I made were only to create a PR in github. I didn't make new changes to gitbook directly. I suspect any errors on the gitbook are actually from when we had a play in Aus. I think you could just revert all changes back to when it was working in Gitbook and continue from there.
Does that sound reasonable to you?

**Comment by RachL** [comment]
@lin-d-hop does this mean we could merge your PR ? I see there is a minor conflict left though.

**Pull request closed without merging**
